jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: al2-emr-ami
      - get: dataworks-aws-ingest-replica
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))
