jobs:
  - name: development
    max_in_flight: 1
    plan:
      - in_parallel:
        - get: terraform-ecr
        - put: meta
          resource: meta-development
        - get: dataworks-behavioural-framework
          trigger: false
        - get: dataworks-aws-ingest-replica
          trigger: true
        - get: al2-emr-ami
          trigger: false
        - get: emr-launcher-release
          trigger: false
      - .: (( inject meta.plan.unit-tests ))
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))
      - .: (( inject meta.plan.e2e-tests ))
        config:
          params:
            TF_WORKSPACE: default
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
