jobs:
  - name: integration
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: dataworks-behavioural-framework
            passed:
              - qa
            trigger: false
          - get: dataworks-aws-ingest-replica
            passed:
              - qa
            trigger: true
          - get: al2-emr-ami
            passed:
              - qa
            trigger: false
          - get: emr-launcher-release
            passed:
              - qa
            trigger: false
      - .: (( inject meta.plan.unit-tests ))
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: integration
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: integration
