jobs:
  - name: dataworks-aws-ingest-replica-pr
    plan:
      - in_parallel:
        - get: dataworks-aws-ingest-replica-pr
          trigger: true
          version: every
        - get: al2-emr-ami
        - get: emr-launcher-release
          trigger: true

      - put: dataworks-aws-ingest-replica-pr
        params:
          path: dataworks-aws-ingest-replica-pr
          status: pending
      - .: (( inject meta.plan.unit-tests ))
        input_mapping:
          dataworks-aws-ingest-replica: dataworks-aws-ingest-replica-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-ingest-replica: dataworks-aws-ingest-replica-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-ingest-replica: dataworks-aws-ingest-replica-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-aws-ingest-replica-pr
          params:
            path: dataworks-aws-ingest-replica-pr
            status: failure
        on_success:
          put: dataworks-aws-ingest-replica-pr
          params:
            path: dataworks-aws-ingest-replica-pr
            status: success
