jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: dataworks-behavioural-framework
            trigger: false
          - get: dataworks-aws-ingest-replica
            trigger: true
            passed:
              - development
          - get: al2-emr-ami
            passed:
              - development
            trigger: false
          - get: emr-launcher-release
            passed:
              - development
            trigger: false
      - .: (( inject meta.plan.unit-tests ))
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.e2e-tests ))
        config:
          params:
            TF_WORKSPACE: 'qa'
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci